apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT
  namespace: $NAMESPACE
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      containers:
        - name: $SERVICE
          image: $USERNAME/property_manager.$SERVICE:$IMAGETAG
          ports:
            - containerPort: 5000
